// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmpPharmacyServer.Data;

#nullable disable

namespace SmpPharmacyServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmpPharmacyServer.Models.Brigade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brigades");
                });

            modelBuilder.Entity("SmpPharmacyServer.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("SmpPharmacyServer.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrigadeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrigadeId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("SmpPharmacyServer.Models.PackageMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicationId")
                        .HasColumnType("integer");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MedicationId");

                    b.HasIndex("PackageId");

                    b.ToTable("PackageMedications");
                });

            modelBuilder.Entity("SmpPharmacyServer.Models.Replenishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrigadeId")
                        .HasColumnType("integer");

                    b.Property<int>("MedicationId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrigadeId");

                    b.HasIndex("MedicationId");

                    b.ToTable("Replenishments");
                });

            modelBuilder.Entity("SmpPharmacyServer.Models.Package", b =>
                {
                    b.HasOne("SmpPharmacyServer.Models.Brigade", "Brigade")
                        .WithMany("Packages")
                        .HasForeignKey("BrigadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brigade");
                });

            modelBuilder.Entity("SmpPharmacyServer.Models.PackageMedication", b =>
                {
                    b.HasOne("SmpPharmacyServer.Models.Medication", "Medication")
                        .WithMany("PackageMedications")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmpPharmacyServer.Models.Package", "Package")
                        .WithMany("PackageMedications")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("SmpPharmacyServer.Models.Replenishment", b =>
                {
                    b.HasOne("SmpPharmacyServer.Models.Brigade", "Brigade")
                        .WithMany("Replenishments")
                        .HasForeignKey("BrigadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmpPharmacyServer.Models.Medication", "Medication")
                        .WithMany("Replenishments")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brigade");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("SmpPharmacyServer.Models.Brigade", b =>
                {
                    b.Navigation("Packages");

                    b.Navigation("Replenishments");
                });

            modelBuilder.Entity("SmpPharmacyServer.Models.Medication", b =>
                {
                    b.Navigation("PackageMedications");

                    b.Navigation("Replenishments");
                });

            modelBuilder.Entity("SmpPharmacyServer.Models.Package", b =>
                {
                    b.Navigation("PackageMedications");
                });
#pragma warning restore 612, 618
        }
    }
}
